"""empty message

Revision ID: 242d2e2a4425
Revises: 
Create Date: 2025-12-04 01:21:28.647058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242d2e2a4425'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_loading', sa.Integer(), nullable=False),
    sa.Column('current_loading', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('IN_QUEUE', 'NEW', 'IN_PROGRESS', 'DONE', name='contact_status'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='fk_contacts_lead_id'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name='fk_contacts_operator_id'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_contacts_source_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads_sources',
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name='fk_leads_sources_lead_id'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_leads_sources_source_id'),
    sa.PrimaryKeyConstraint('lead_id', 'source_id')
    )
    op.create_table('operator_source_priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name='fk_priorities_operator_id'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name='fk_priorities_source_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator_source_priorities')
    op.drop_table('leads_sources')
    op.drop_table('contacts')
    op.drop_table('sources')
    op.drop_table('operators')
    op.drop_table('leads')
    # ### end Alembic commands ###
